export const CHANGE_USER_INPUT_TEXT="CHANGE_USER_INPUT_TEXT";
export const CHANGE_USER_INPUT_STYLE="CHANGE_USER_INPUT_STYLE";
export const CHANGE_USER_COLOR_SELECT="CHANGE_USER_COLOR_SELECT";
export const CHANGE_USER_FONT_SIZE="CHANGE_USER_FONT_SIZE";